cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    cc:
      email: cc
      name: cc
      password: $2b$12$MSzgrdYopYt36Yr493i4Fe3TxfvWVcXBme65qq80FoFeB7exirzfq
    moo:
      name: MOO
      password: $2b$12$GndD9vJFvOjIFkYXW79YaOPvqaVPHRNSo2bZ3nGja8NqaBGxL.pFC
    moo2:
      name: MOO2
      password: $2b$12$hgcBpZWNxm/9X87Fz89tuOhzT6hzYDAoOAcDX6.EZ8dA.iD5x2OxW
    xx:
      email: xx
      name: xx
      password: $2b$12$7xG5GghTbrMmRJful5foHuhhKJ2taQmp769FFau5gyWSYKEBU.p46
preauthorized:
  emails:
  - cymoo12@gmail.com
