cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    '123':
      email: '123'
      name: '123'
      password: $2b$12$jwGPHRWTOdRIpnVQR1GXxu3yQGtPwLFixbeWw1eRv46SbMTo/GfCi
    '12345':
      email: '12345'
      name: '12345'
      password: $2b$12$y0MQHyTg6QtvrLq4oXNZ2OZBpF28TlBlV8GHnRb4nBzKiYdFSTTxG
    '123456':
      email: '123456'
      name: '123456'
      password: $2b$12$cAordvPx9NhLcAg2hCD/fuqlYlk/uQpd5vOEL.9aTa1PtRgKmLxsi
    '456':
      email: '456'
      name: '456'
      password: $2b$12$Mh8S.2/IFDM/uIKm1IsQtuF2Phm7E9I.XBMSqPy0jbhA7b0RUrcOS
    aaaa:
      email: aaaa
      name: aaaa
      password: $2b$12$ItOHYaGDCjWHZYcrmcVdx.h3GU0dPkB0SHLYVB0ttYmkggWx4tLa2
    cc:
      email: cc
      name: cc
      password: $2b$12$MSzgrdYopYt36Yr493i4Fe3TxfvWVcXBme65qq80FoFeB7exirzfq
    moo:
      name: MOO
      password: $2b$12$GndD9vJFvOjIFkYXW79YaOPvqaVPHRNSo2bZ3nGja8NqaBGxL.pFC
    moo2:
      name: MOO2
      password: $2b$12$hgcBpZWNxm/9X87Fz89tuOhzT6hzYDAoOAcDX6.EZ8dA.iD5x2OxW
    xx:
      email: xx
      name: xx
      password: $2b$12$7xG5GghTbrMmRJful5foHuhhKJ2taQmp769FFau5gyWSYKEBU.p46
    xxx:
      email: xxx
      name: xxx
      password: $2b$12$NVdbETHfjke3/DfnYkkPtut7Wc.T8qWkrfCC4R/Ld14hpRntGwEKe
preauthorized:
  emails:
  - cymoo12@gmail.com
